### PR TITLE
adds support for aws session token

### PR DESCRIPTION
**Pull request by anaik-zam**
AWS multifactor authentication provides a session token which needs to be passed to boto session object to authenticate. This PR adds support to pass the session token as an optional env var.

### CODE REVIEW

**Comment by JSchulte01** [comment]
+1 for this - particularly important for multi-account multi-role IAM architectures.

**Comment by matdue** [comment]
+1 - patch works as intended

**Comment by naiquevin** [comment]
@anaik-zam Thanks for the PR and @matdue: Thanks for verifying. However, I want to merge the other PR (#4) first as it was opened earlier. I think it has conflicting changes with this one. Will find time soon for verifying and merging both. Sorry for the trouble.

**Comment by naiquevin** [comment]
@anaik-zam: I have merged the other PR. Can you please rebase your branch with the latest master.

**Comment by anaik-zam** [comment]
@naiquevin Sorry for the delay, kinda slipped through the cracks. I've rebased with the latest master

**Comment by naiquevin** [comment]
Thanks @anaik-zam

**Pull request merged**
